jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - script: npm install -g windows-build-tools
    displayName: 'npm install -g windows-build-tools'
  - template: build/azure-pipelines/continuous-build-oni.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build/azure-pipelines/continuous-build-oni.yml

- job: macOS
  pool:
    vmImage: macOS 10.14
  steps:
  - template: build/azure-pipelines/continuous-build-oni.yml
