jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x'
      addToPath: true
  - template: build/azure-pipelines/continuous-build-oni.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x'
      addToPath: true
  - template: build/azure-pipelines/continuous-build-oni.yml

- job: macOS
  pool:
    vmImage: macOS 10.14
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x'
      addToPath: true
  - template: build/azure-pipelines/continuous-build-oni.yml
